apiVersion: v1
data:
  DB_HOST: cG9zdGdyZXMuZGV2LnN2Yy5jbHVzdGVyLmxvY2Fs
  DB_NAME: b3JkZXJzX2Ri
  DB_PASSWORD: U2VjdXJlUGFzczEyMyE=
  DB_PORT: NTQzMg==
  DB_USER: ZGV2dXNlcg==
kind: Secret
metadata:
  name: db-credentials
  namespace: dev
